//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoutiqueParfums
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartProduct
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdCart { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
